In [1]:
import pandas as pd

In [2]:
df_dpe_2024 = pd.read_csv(
    "../Data/Input/dpe_95_2024.csv"
)

df_dpe_2025 = pd.read_csv(
    "../Data/Input/dpe_95_2025.csv"
)

In [3]:
print("2024 :", df_dpe_2024.shape)
print("2025 :", df_dpe_2025.shape)

2024 : (73234, 23)
2025 : (57609, 23)

In [4]:
print(df_dpe_2024.columns.tolist())

['numero_dpe', 'date_etablissement_dpe', 'etiquette_dpe', 'etiquette_ges', 'periode_construction', 'nom_commune_ban', 'code_postal_ban', 'code_insee_ban', 'code_departement_ban', 'qualite_isolation_enveloppe', 'qualite_isolation_murs', 'qualite_isolation_menuiseries', 'qualite_isolation_plancher bas', 'type_energie_principale_chauffage', 'type_generateur_chauffage_principal', 'conso_5_usages_par_m2_ep', 'type_batiment', 'surface_habitable_logement', 'annee_construction', 'indicateur_confort_ete', 'type_ventilation', 'version_dpe', 'presence_production_pv']

In [5]:
df_dpe_2024["annee_source"] = 2024
df_dpe_2025["annee_source"] = 2025

df_dpe = pd.concat(
    [df_dpe_2024, df_dpe_2025],
    ignore_index=True
)

print(df_dpe.shape)

(130843, 24)

In [6]:
df_dpe = df_dpe.rename(
    columns={
        "qualite_isolation_plancher bas":
        "qualite_isolation_plancher_bas"
    }
)

In [7]:
df_dpe.info()
(df_dpe.isna().mean() * 100).sort_values(ascending=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130843 entries, 0 to 130842
Data columns (total 24 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   numero_dpe                           130843 non-null  object
 1   date_etablissement_dpe               130843 non-null  object
 2   etiquette_dpe                        130843 non-null  object
 3   etiquette_ges                        130843 non-null  object
 4   periode_construction                 130843 non-null  object
 5   nom_commune_ban                      130843 non-null  object
 6   code_postal_ban                      130843 non-null  int64
 7   code_insee_ban                       130843 non-null  int64
 8   code_departement_ban                 130843 non-null  int64
 9   qualite_isolation_enveloppe          130843 non-null  object
 10  qualite_isolation_murs               130779 non-null  object
 11  qualite_isolation_menuiseries        130843 non-null  object
 12  qualite_isolation_plancher_bas       126835 non-null  object
 13  type_energie_principale_chauffage    130843 non-null  object
 14  type_generateur_chauffage_principal  38402 non-null   object
 15  conso_5_usages_par_m2_ep             130843 non-null  float64
 16  type_batiment                        130843 non-null  object
 17  surface_habitable_logement           127307 non-null  float64
 18  annee_construction                   74366 non-null   float64
 19  indicateur_confort_ete               62774 non-null   object
 20  type_ventilation                     130835 non-null  object
 21  version_dpe                          130843 non-null  float64
 22  presence_production_pv               11679 non-null   float64
 23  annee_source                         130843 non-null  int64
dtypes: float64(5), int64(4), object(15)
memory usage: 24.0+ MB

presence_production_pv                 91.074035
type_generateur_chauffage_principal    70.650321
indicateur_confort_ete                 52.023417
annee_construction                     43.163945
qualite_isolation_plancher_bas          3.063213
surface_habitable_logement              2.702475
qualite_isolation_murs                  0.048914
type_ventilation                        0.006114
type_energie_principale_chauffage       0.000000
version_dpe                             0.000000
type_batiment                           0.000000
conso_5_usages_par_m2_ep                0.000000
numero_dpe                              0.000000
date_etablissement_dpe                  0.000000
qualite_isolation_menuiseries           0.000000
qualite_isolation_enveloppe             0.000000
code_departement_ban                    0.000000
code_insee_ban                          0.000000
code_postal_ban                         0.000000
nom_commune_ban                         0.000000
periode_construction                    0.000000
etiquette_ges                           0.000000
etiquette_dpe                           0.000000
annee_source                            0.000000
dtype: float64

In [8]:
df_dpe["code_postal_ban"] = df_dpe["code_postal_ban"].astype(str)
df_dpe["code_insee_ban"] = df_dpe["code_insee_ban"].astype(str)
df_dpe["code_departement_ban"] = df_dpe["code_departement_ban"].astype(str)

df_dpe["date_etablissement_dpe"] = pd.to_datetime(
    df_dpe["date_etablissement_dpe"],
    errors="coerce"
)

In [9]:
print("Nombre de lignes :", len(df_dpe))
print("Nombre de DPE uniques :", df_dpe["numero_dpe"].nunique())
print("Doublons :", df_dpe["numero_dpe"].duplicated().sum())

Nombre de lignes : 130843
Nombre de DPE uniques : 130843
Doublons : 0

In [10]:
colonnes_utiles = [
    "numero_dpe",
    "date_etablissement_dpe",
    "annee_source",
    "etiquette_dpe",
    "etiquette_ges",
    "conso_5_usages_par_m2_ep",
    "type_batiment",
    "surface_habitable_logement",
    "periode_construction",
    "nom_commune_ban",
    "code_postal_ban",
    "code_insee_ban",
    "qualite_isolation_enveloppe",
    "qualite_isolation_murs",
    "qualite_isolation_menuiseries",
    "qualite_isolation_plancher_bas",
    "type_energie_principale_chauffage",
    "type_ventilation"
]

df_dpe_clean = df_dpe[colonnes_utiles].copy()

print(df_dpe_clean.shape)

(130843, 18)

In [11]:
df_dpe_clean = df_dpe_clean.rename(
    columns={
        "nom_commune_ban": "commune",
        "code_postal_ban": "code_postal",
        "code_insee_ban": "code_insee"
    }
)

df_dpe_clean.head()

,numero_dpe,date_etablissement_dpe,annee_source,etiquette_dpe,etiquette_ges,conso_5_usages_par_m2_ep,type_batiment,surface_habitable_logement,periode_construction,commune,code_postal,code_insee,qualite_isolation_enveloppe,qualite_isolation_murs,qualite_isolation_menuiseries,qualite_isolation_plancher_bas,type_energie_principale_chauffage,type_ventilation
0,2495E4275343B,2024-12-02,2024,E,C,348.5,appartement,28.4,avant 1948,Montmorency,95160,95428,insuffisante,insuffisante,moyenne,très bonne,Électricité,Ventilation par ouverture des fenêtres
1,2495E3512145H,2024-10-03,2024,D,B,242.4,maison,85.0,1948-1974,Goussainville,95190,95280,bonne,moyenne,moyenne,insuffisante,Électricité,Ventilation par ouverture des fenêtres
2,2495E0905509B,2024-03-12,2024,F,F,407.5,maison,81.0,1948-1974,Sannois,95110,95582,insuffisante,insuffisante,insuffisante,bonne,Gaz naturel,Ventilation par entrées d'air hautes et basses
3,2495E1303829B,2024-04-05,2024,C,A,170.7,maison,240.0,1948-1974,Nesles-la-Vallée,95690,95446,insuffisante,insuffisante,très bonne,insuffisante,Bois – Bûches,VMC SF Auto réglable avant 1982
4,2495E1387089J,2024-04-11,2024,E,D,299.0,maison,112.0,1948-1974,Fosses,95470,95250,insuffisante,insuffisante,moyenne,moyenne,Gaz naturel,Ventilation par ouverture des fenêtres

In [12]:
# Repérer les codes INSEE associés à plusieurs écritures de commune
communes_uniques = (
    df_dpe_clean[["code_insee", "commune"]]
    .drop_duplicates()
)

communes_variantes = communes_uniques[
    communes_uniques["code_insee"].duplicated(keep=False)
].sort_values(["code_insee", "commune"])

communes_variantes

       code_insee                   commune
30535       95091               BouffÃ mont
177         95091                Bouffémont
828         95101                Bray-et-LÃ
1198        95101                Bray-et-Lû
87835       95170               CondÃ court
3278        95170                Condécourt
107136      95205                   Ã couen
235         95205                    Écouen
113740      95213              Ã piais-Rhus
4331        95213               Épiais-Rhus
29707       95218                   Ã ragny
424         95218                    Éragny
74037       95229                Ã zanville
368         95229                 Ézanville
119176      95253             FrÃ mainville
4211        95253              Frémainville
7282        95268       Garges-lÃ¨s-Gonesse
86          95268        Garges-lès-Gonesse
28021       95394            MÃ ry-sur-Oise
61          95394             Méry-sur-Oise
82380       95424  Montigny-lÃ¨s-Cormeilles
360         95424   Montigny-lès-Cormeilles
94677       95563        Saint-Leu-la-Foret
25557       95563       Saint-Leu-la-ForÃ t
506         95563        Saint-Leu-la-Forêt
38206       95572      Saint-Ouen-l'AumÃ ne
225         95572       Saint-Ouen-l'Aumône
117641      95651                 VÃ theuil
180         95651                  Vétheuil

In [13]:
correction_communes = {
    "BouffÃ mont": "Bouffémont",
    "Bray-et-LÃ": "Bray-et-Lû",
    "CondÃ court": "Condécourt",
    "Ã couen": "Écouen",
    "Ã piais-Rhus": "Épiais-Rhus",
    "Ã ragny": "Éragny",
    "Ã zanville": "Ézanville",
    "FrÃ mainville": "Frémainville",
    "Garges-lÃ¨s-Gonesse": "Garges-lès-Gonesse",
    "MÃ ry-sur-Oise": "Méry-sur-Oise",
    "Montigny-lÃ¨s-Cormeilles": "Montigny-lès-Cormeilles",
    "Saint-Leu-la-Foret": "Saint-Leu-la-Forêt",
    "Saint-Leu-la-ForÃ t": "Saint-Leu-la-Forêt",
    "Saint-Ouen-l'AumÃ ne": "Saint-Ouen-l'Aumône",
    "VÃ theuil": "Vétheuil"
}

df_dpe_clean["commune"] = (
    df_dpe_clean["commune"]
    .replace(correction_communes)
)

In [14]:
controle_communes = (
    df_dpe_clean
    .groupby("code_insee")["commune"]
    .nunique()
)

print("Codes avec plusieurs noms :", (controle_communes > 1).sum())
print("Nombre de codes INSEE :", df_dpe_clean["code_insee"].nunique())
print("Nombre de lignes DPE :", len(df_dpe_clean))

Codes avec plusieurs noms : 0
Nombre de codes INSEE : 183
Nombre de lignes DPE : 130843

In [15]:
distribution_dpe = (
    df_dpe_clean["etiquette_dpe"]
    .value_counts()
    .sort_index()
)

print(distribution_dpe)

print(
    (
        df_dpe_clean["etiquette_dpe"]
        .value_counts(normalize=True)
        .sort_index() * 100
    ).round(2)
)

etiquette_dpe
A      350
B     4958
C    57480
D    41243
E    18244
F     5237
G     3331
Name: count, dtype: int64
etiquette_dpe
A     0.27
B     3.79
C    43.93
D    31.52
E    13.94
F     4.00
G     2.55
Name: proportion, dtype: float64

In [16]:
df_dpe_clean["passoire_fg"] = (
    df_dpe_clean["etiquette_dpe"]
    .isin(["F", "G"])
).astype(int)

df_dpe_clean["passoire_fg"].value_counts()

passoire_fg
0    122275
1      8568
Name: count, dtype: int64

In [17]:
df_dpe_commune = (
    df_dpe_clean
    .groupby(["code_insee", "commune"])
    .agg(
        nombre_dpe=("numero_dpe", "count"),
        nombre_passoires_fg=("passoire_fg", "sum"),
        consommation_moyenne=(
            "conso_5_usages_par_m2_ep",
            "mean"
        )
    )
    .reset_index()
)

df_dpe_commune["part_passoires_fg_pct"] = (
    df_dpe_commune["nombre_passoires_fg"]
    / df_dpe_commune["nombre_dpe"]
    * 100
).round(2)

df_dpe_commune.head()

,code_insee,commune,nombre_dpe,nombre_passoires_fg,consommation_moyenne,part_passoires_fg_pct
0,95002,Ableiges,66,9,227.157576,13.64
1,95008,Aincourt,89,8,223.051685,8.99
2,95011,Ambleville,19,11,327.915789,57.89
3,95012,Amenucourt,12,5,287.841667,41.67
4,95014,Andilly,207,18,191.328019,8.70

In [18]:
df_insee_95 = pd.read_csv(
    "../Data/Output/insee_logement_val_doise_2022.csv",
    dtype={"code_insee": str}
)

In [19]:
print(
    "Communes DPE :",
    df_dpe_commune["code_insee"].nunique()
)

print(
    "Communes INSEE :",
    df_insee_95["code_insee"].nunique()
)

Communes DPE : 183
Communes INSEE : 183

In [20]:
codes_dpe = set(df_dpe_commune["code_insee"])
codes_insee = set(df_insee_95["code_insee"])

print(
    "Présents dans DPE mais pas INSEE :",
    codes_dpe - codes_insee
)

print(
    "Présents dans INSEE mais pas DPE :",
    codes_insee - codes_dpe
)

Présents dans DPE mais pas INSEE : set()
Présents dans INSEE mais pas DPE : set()

In [21]:
df_dpe_clean.to_csv(
    "../Data/Output/dpe_95_2024_2025_clean.csv",
    index=False,
    date_format="%Y-%m-%d",
    encoding="utf-8"
)

df_dpe_commune.to_csv(
    "../Data/Output/dpe_commune_95_2024_2025.csv",
    index=False,
    encoding="utf-8"
)

print(
    "DPE détaillé :",
    df_dpe_clean.shape
)

print(
    "DPE communes :",
    df_dpe_commune.shape
)

DPE détaillé : (130843, 19)
DPE communes : (183, 6)

In [22]:
print(df_dpe_clean.shape)

(130843, 19)

In [23]:
df_test = pd.read_csv(
    "../Data/Output/dpe_95_2024_2025_clean.csv",
    encoding="utf-8"
)

df_test["qualite_isolation_enveloppe"].value_counts()

qualite_isolation_enveloppe
insuffisante    61512
moyenne         32105
bonne           24354
très bonne      12872
Name: count, dtype: int64