In [1]:
import requests
import pandas as pd

In [2]:
departement = "95"

In [3]:
url_api = (
    "https://data.ademe.fr/data-fair/api/v1/"
    "datasets/liste-des-entreprises-rge-2/lines"
)

params = {
    "code_postal_starts": departement,
    "size": 5
}

In [4]:
response = requests.get(
    url_api,
    params=params
)

if response.status_code == 200:
    print("Connexion réussie - code 200")
else:
    print("Erreur :", response.status_code)

Connexion réussie - code 200

In [5]:
data = response.json()

print(data.keys())

dict_keys(['total', 'next', 'results'])

In [6]:
print("Nombre total de lignes trouvées :", data["total"])

df_test = pd.DataFrame(data["results"])

df_test

Nombre total de lignes trouvées : 1607

,site_internet,lien_date_fin,code_postal,_geopoint,commune,latitude,domaine,nom_entreprise,nom_qualification,organisme,...,code_qualification,_rand,particulier,adresse,nom_certificat,email,lien_date_debut,longitude,_score,_id
0,,2099-01-01,95170,"48.974908,2.333",DEUIL-LA-BARRE,48.974908,Architecte,AGARAM,Architecte sur le site faire.fr (2),cnoa,...,2,608197,True,1 RUE DE LA FONTAINE DU GUE,Tableau de l´Ordre,agaram.architectes@gmail.com,2022-09-14,2.333000,None,S210548-4623128-2-2022-09-30
1,http://www.archi-bien.fr/,2099-01-01,95410,"48.983248,2.342932",GROSLAY,48.983248,Architecte,MARIE LEGER ARCHITECTE,Architecte sur le site faire.fr (2),cnoa,...,2,21430,True,2 RUE JULES VINCENT,Tableau de l´Ordre,contact@archi-bien.fr,2019-09-06,2.342932,None,S213289-4667095-2-2022-10-28
2,http://sandrarazavet.wix.com/sararchitecture,2099-01-01,95220,"48.986686,2.17209",HERBLAY,48.986686,Architecte,SARA ARCHITECTURE,Architecte sur le site faire.fr (2),cnoa,...,2,228186,True,39 BOULEVARD CLEMENCEAU,Tableau de l´Ordre,sandra.djoudi@wanadoo.fr,2020-11-16,2.172090,None,S211422-4627315-2-2023-05-11
3,,2099-01-01,95500,"48.993332,2.452986",GONESSE,48.993332,Architecte,HALLAK AND NASSER ARCHITECTS WORKSHOP,Architecte sur le site faire.fr (2),cnoa,...,2,95826,True,3 AVENUE MARECHAL JUIN,Tableau de l´Ordre,mnhallak@gmail.com,2019-06-25,2.452986,None,S210898-4624866-2-2021-10-07
4,,2099-01-01,95640,"49.143528,1.979532",MARINES,49.143528,Architecte,CABINET D'ETUDES D'ARCHITECTURE ET D'URBANISME,Architecte sur le site faire.fr (2),cnoa,...,2,15135,True,5 RUE DE CHARS,Tableau de l´Ordre,jean-francois.hole@wanadoo.fr,2019-09-06,1.979532,None,S206003-4600487-2-2021-10-07

In [7]:
params = {
    "code_postal_starts": departement,
    "size": 10000
}

response = requests.get(
    url_api,
    params=params
)

data = response.json()

df_rge_api = pd.DataFrame(
    data["results"]
)

print("Nombre de lignes récupérées :", len(df_rge_api))
print("Nombre total annoncé par l'API :", data["total"])

Nombre de lignes récupérées : 1607
Nombre total annoncé par l'API : 1607

In [8]:
print("Dimensions :", df_rge_api.shape)

print("\nColonnes :")
print(df_rge_api.columns.tolist())

Dimensions : (1607, 25)

Colonnes :
['site_internet', 'lien_date_fin', 'code_postal', '_geopoint', 'commune', 'latitude', 'domaine', 'nom_entreprise', 'nom_qualification', 'organisme', 'telephone', '_i', 'url_qualification', 'siret', 'meta_domaine', 'code_qualification', '_rand', 'particulier', 'adresse', 'nom_certificat', 'email', 'lien_date_debut', 'longitude', '_score', '_id']

In [9]:
nom_fichier = f"../Data/Input/rge_api_{departement}_raw.csv"

df_rge_api.to_csv(
    nom_fichier,
    index=False
)

print("Fichier exporté :", nom_fichier)

Fichier exporté : ../Data/Input/rge_api_95_raw.csv

In [10]:
colonnes_utiles = [
    "siret",
    "nom_entreprise",
    "adresse",
    "code_postal",
    "commune",
    "code_qualification",
    "nom_qualification",
    "domaine",
    "meta_domaine",
    "organisme",
    "lien_date_debut",
    "lien_date_fin"
]

df_rge_api_clean = df_rge_api[colonnes_utiles].copy()

print("Dimensions :", df_rge_api_clean.shape)
df_rge_api_clean.head()

Dimensions : (1607, 12)

,siret,nom_entreprise,adresse,code_postal,commune,code_qualification,nom_qualification,domaine,meta_domaine,organisme,lien_date_debut,lien_date_fin
0,79118512700010,AGARAM,1 RUE DE LA FONTAINE DU GUE,95170,DEUIL-LA-BARRE,2,Architecte sur le site faire.fr (2),Architecte,Rénovation globale,cnoa,2022-09-14,2099-01-01
1,82154955700014,MARIE LEGER ARCHITECTE,2 RUE JULES VINCENT,95410,GROSLAY,2,Architecte sur le site faire.fr (2),Architecte,Rénovation globale,cnoa,2019-09-06,2099-01-01
2,80105516100013,SARA ARCHITECTURE,39 BOULEVARD CLEMENCEAU,95220,HERBLAY,2,Architecte sur le site faire.fr (2),Architecte,Rénovation globale,cnoa,2020-11-16,2099-01-01
3,79531109100016,HALLAK AND NASSER ARCHITECTS WORKSHOP,3 AVENUE MARECHAL JUIN,95500,GONESSE,2,Architecte sur le site faire.fr (2),Architecte,Rénovation globale,cnoa,2019-06-25,2099-01-01
4,30918116200038,CABINET D'ETUDES D'ARCHITECTURE ET D'URBANISME,5 RUE DE CHARS,95640,MARINES,2,Architecte sur le site faire.fr (2),Architecte,Rénovation globale,cnoa,2019-09-06,2099-01-01

In [11]:
# Les identifiants sont convertis en texte
df_rge_api_clean["siret"] = df_rge_api_clean["siret"].astype(str)
df_rge_api_clean["code_postal"] = df_rge_api_clean["code_postal"].astype(str)

# Conversion des dates
df_rge_api_clean["lien_date_debut"] = pd.to_datetime(
    df_rge_api_clean["lien_date_debut"],
    errors="coerce"
)

df_rge_api_clean["lien_date_fin"] = pd.to_datetime(
    df_rge_api_clean["lien_date_fin"],
    errors="coerce"
)

print(df_rge_api_clean.dtypes)

siret                         object
nom_entreprise                object
adresse                       object
code_postal                   object
commune                       object
code_qualification            object
nom_qualification             object
domaine                       object
meta_domaine                  object
organisme                     object
lien_date_debut       datetime64[ns]
lien_date_fin         datetime64[ns]
dtype: object

In [12]:
nom_fichier_clean = f"../Data/Output/rge_api_{departement}_clean.csv"

df_rge_api_clean.to_csv(
    nom_fichier_clean,
    index=False
)

print("Fichier exporté :", nom_fichier_clean)

Fichier exporté : ../Data/Output/rge_api_95_clean.csv